version: '3.9'

services:
  app:
    build: .
    container_name: had-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - TYPEORM_HOST=postgres
      - TYPEORM_PORT=5432
      - TYPEORM_DATABASE=had
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=rasmy4535
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rasmy4535
      POSTGRES_DB: had
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:
